#!/usr/bin/env python3
import os

from hammer.vlsi import CLIDriver, HammerTool, HammerToolHookAction

from typing import Dict, Callable, Optional, List

def global_power(x: HammerTool) -> bool:
    x.append('''
        set_db init_power_nets {VDD}
        set_db init_ground_nets {VSS}
        connect_global_net VDD -type pg_pin -pin vdd -override
        connect_global_net VSS -type pg_pin -pin vss -override
    ''')
    return True

def eco_changes(x: HammerTool) -> bool:
    # This is a place for ECO changes that are not in the original design
    # For example, if you want to change the size of a cell, you can do it here
    # or if you want to add a new cell, you can do it here
    # This is a place for manual changes that are not in the original design
    
    # in order to prevent DRC (metal spacing) violations at the SRAM ports when lowest routing layer is Met2 because by default, Vias will be stamped on top of ports (on M1) from Met1 -> Met2, which creates metal spacing violations between the vias on the ports - more details: https://ucb-bar.slack.com/archives/C04BT3QEW4C/p1751308674571229
    x.append("""
            set_db design_bottom_routing_layer met1
            route_eco -fix_drc
            """)
    return True

class ProjectDriver(CLIDriver):
    def get_extra_par_hooks(self) -> List[HammerToolHookAction]:
        extra_hooks = [            
            HammerTool.make_post_insertion_hook("floorplan_design", global_power),
            HammerTool.make_pre_insertion_hook("write_design", eco_changes)
        ]
        return extra_hooks

if __name__ == '__main__':
    ProjectDriver().main()